name: Terraform Security Static Analysis
on: 'push'

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform security scan
        uses: triat/terraform-security-scan@v1
        env:
          INPUT_TFSEC_EXCLUDE: AWS006

